# Generated by Django 4.2.7 on 2025-10-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["stock", "date"], name="stocks_pric_stock_i_c871e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(fields=["date"], name="stocks_pric_date_917e57_idx"),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(fields=["ticker"], name="stocks_stoc_ticker_5df4c9_idx"),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(fields=["sector"], name="stocks_stoc_sector_6c2055_idx"),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["last_updated"], name="stocks_stoc_last_up_3b4825_idx"
            ),
        ),
    ]
