# Generated by Django 4.2.7 on 2025-10-28 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0002_pricehistory_stocks_pric_stock_i_c871e2_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PriceHistory",
        ),
    ]
