# Generated by Django 4.2.7 on 2025-10-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0003_remove_price_history"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stock",
            options={"ordering": ["ticker"]},
        ),
        migrations.RemoveIndex(
            model_name="stock",
            name="stocks_stoc_ticker_5df4c9_idx",
        ),
        migrations.RemoveIndex(
            model_name="stock",
            name="stocks_stoc_sector_6c2055_idx",
        ),
        migrations.RemoveIndex(
            model_name="stock",
            name="stocks_stoc_last_up_3b4825_idx",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="sector",
        ),
        migrations.AlterField(
            model_name="stock",
            name="current_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="stock",
            name="ticker",
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
