# Generated by Django 4.2.7 on 2025-10-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0004_alter_stock_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(fields=["ticker"], name="stocks_stoc_ticker_5df4c9_idx"),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["current_price"], name="stocks_stoc_current_566855_idx"
            ),
        ),
    ]
