# Generated by Django 4.2.7 on 2025-10-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_remove_transaction_total_amount_transaction_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="price_per_share",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
