# Generated by Django 4.2.7 on 2025-10-28 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portfolio", "0005_auto_20251027_2308"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="total_amount",
        ),
        migrations.AlterUniqueTogether(
            name="portfolio",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(
                fields=["user", "name"], name="portfolio_p_user_id_1eb9a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["portfolio", "stock"], name="portfolio_t_portfol_f5ddf9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_date"], name="portfolio_t_transac_374fda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["transaction_type"], name="portfolio_t_transac_dded9c_idx"
            ),
        ),
    ]
