# Generated by Django 4.2.7 on 2025-10-28 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0004_alter_stock_options_and_more"),
        ("portfolio", "0006_remove_transaction_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["date"]},
        ),
        migrations.RemoveIndex(
            model_name="portfolio",
            name="portfolio_p_user_id_1eb9a8_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="portfolio_t_portfol_f5ddf9_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="portfolio_t_transac_374fda_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="portfolio_t_transac_dded9c_idx",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="price_per_share",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="transaction_date",
        ),
        migrations.AddField(
            model_name="transaction",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="ticker",
            field=models.CharField(db_index=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="quantity",
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="stocks.stock",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("BUY", "Buy"), ("SELL", "Sell")], db_index=True, max_length=4
            ),
        ),
    ]
