# Generated by Django 4.2.7 on 2025-10-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
