# Generated by Django 4.2.7 on 2025-10-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0008_alter_transaction_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="quantity",
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
