# Generated by Django 4.2.7 on 2025-10-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0009_alter_transaction_quantity"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["portfolio", "ticker", "date"],
                name="portfolio_t_portfol_2b6228_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["portfolio", "transaction_type"],
                name="portfolio_t_portfol_eab879_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["ticker", "date"], name="portfolio_t_ticker_5060de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["portfolio", "date"], name="portfolio_t_portfol_412c13_idx"
            ),
        ),
    ]
